import type { ModulePageConfig } from '@/components/pages/module-page-layout';

export const MODULE_CONFIGS: Record<string, ModulePageConfig> = {
  tech: {
    title: 'Technology Intelligence',
    subtitle: 'Hardware, cloud, robotics, semiconductors and product innovation',
    icon: '🚀',
    iconClass: 'icon-tech',
    category: 'tech',
    showLive: true,
    subcategories: ['All', 'Hardware', 'Cloud', 'Robotics', 'Quantum', 'Space', 'Semiconductors'],
  },
  ai: {
    title: 'AI & Machine Learning',
    subtitle: 'Large language models, AI infrastructure, MLOps and automation',
    icon: '🤖',
    iconClass: 'icon-ai',
    category: 'ai',
    showLive: true,
    subcategories: ['All', 'Models', 'Research', 'Tools', 'Agents', 'Infrastructure'],
  },
  cybersecurity: {
    title: 'Cybersecurity Intelligence',
    subtitle: 'Breaches, vulnerabilities, threat intel and incident response updates',
    icon: '🛡️',
    iconClass: 'icon-cyber',
    moduleId: 'cybersecurity',
    showLive: true,
    subcategories: [
      'All',
      'Breaches & Incidents',
      'Vulnerabilities & CVEs',
      'Threat Intel',
      'Ransomware & Malware',
      'Security Research',
    ],
  },
  github: {
    title: 'GitHub Developer Intelligence',
    subtitle: 'Trending repositories, open-source tools and developer ecosystems',
    icon: '💻',
    iconClass: 'icon-github',
    category: 'github',
    showLive: true,
    subcategories: ['All', 'AI', 'DevOps', 'Web Dev', 'Languages', 'Tools'],
  },
  research: {
    title: 'Science & Research',
    subtitle: 'Academic papers, engineering breakthroughs and space research',
    icon: '🔬',
    iconClass: 'icon-science',
    category: 'research',
    subcategories: ['All', 'Academic Papers', 'Engineering', 'Space Research'],
  },
  startups: {
    title: 'Startups & VC',
    subtitle: 'Funding rounds, IPOs, venture activity and startup launches',
    icon: '💼',
    iconClass: 'icon-startups',
    category: 'startups',
    subcategories: ['All', 'Funding Rounds', 'IPOs', 'VC Activity', 'Launches'],
  },
  crypto: {
    title: 'Crypto & DeFi',
    subtitle: 'Bitcoin, Ethereum, DeFi protocols, regulations and market moves',
    icon: '₿',
    iconClass: 'icon-crypto',
    category: 'crypto',
    subcategories: ['All', 'Bitcoin', 'Ethereum', 'DeFi', 'Regulations', 'Exchanges'],
  },
  trading: {
    title: 'Financial Trading',
    subtitle: 'Forex, commodities, ETFs, futures and macro market events',
    icon: '📈',
    iconClass: 'icon-trading',
    category: 'trading',
    subcategories: ['All', 'Forex', 'Commodities', 'ETFs', 'Futures', 'Earnings'],
  },
  global: {
    title: 'Global Geopolitics',
    subtitle: 'Government decisions, economic events and international agreements',
    icon: '🌍',
    iconClass: 'icon-geopolitics',
    category: 'global',
    subcategories: ['All', 'Government', 'Economic Events', 'International'],
  },
  clouddevops: {
    title: 'Cloud & DevOps Engineering',
    subtitle: 'Cloud providers, Kubernetes, containerization and CI/CD pipelines',
    icon: '☁️',
    iconClass: 'icon-cloud',
    moduleId: 'clouddevops',
    showLive: true,
    subcategories: ['All', 'Cloud Providers', 'DevOps Infrastructure'],
  },
  forex: {
    title: 'Forex Market',
    subtitle: 'Currency markets, central banks and economic indicators',
    icon: '💱',
    iconClass: 'icon-forex',
    moduleId: 'forex',
    showLive: true,
    subcategories: [
      'All',
      'Central Bank Decisions',
      'Currency Markets',
      'Interest Rates',
      'Inflation Reports',
      'Economic Indicators',
    ],
  },
  gold: {
    title: 'Gold & Precious Metals',
    subtitle: 'Gold, silver, platinum, mining and commodities market analysis',
    icon: '🥇',
    iconClass: 'icon-gold',
    moduleId: 'gold',
    showLive: true,
    subcategories: [
      'All',
      'Gold',
      'Silver',
      'Platinum & Palladium',
      'Mining & Supply',
      'Commodities & Energy',
      'Market Analysis',
    ],
  },
};
